-- MySQL Script generated by MySQL Workbench
-- Qui 12 Abr 2018 19:47:02 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema napoli2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `napoli2` ;

-- -----------------------------------------------------
-- Schema napoli2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `napoli2` DEFAULT CHARACTER SET utf8 ;
USE `napoli2` ;

-- -----------------------------------------------------
-- Table `napoli2`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`country` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`country` (
  `code` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`user` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  `pw_hash` VARCHAR(255) NULL,
  `affiliation` VARCHAR(255) NULL,
  `is_admin` TINYINT(1) NULL,
  `country_code` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_country1_idx` (`country_code` ASC),
  CONSTRAINT `fk_user_country1`
    FOREIGN KEY (`country_code`)
    REFERENCES `napoli2`.`country` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`status` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`status` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NULL,
  `css_style` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`project_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`project_type` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`project_type` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `days_available` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`project` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_code` VARCHAR(45) NULL,
  `project_type_id` TINYINT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `status_id` TINYINT UNSIGNED NOT NULL,
  `start_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `is_fixed` TINYINT(1) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `job_code_UNIQUE` (`job_code` ASC),
  INDEX `fk_project_user1_idx` (`user_id` ASC),
  INDEX `fk_project_status1_idx` (`status_id` ASC),
  INDEX `fk_project_project_type1_idx` (`project_type_id` ASC),
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `napoli2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `napoli2`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_project_type1`
    FOREIGN KEY (`project_type_id`)
    REFERENCES `napoli2`.`project_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`compose_dataset_proj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`compose_dataset_proj` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`compose_dataset_proj` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `searched_pdb` CHAR(4) NULL,
  `searched_chain` CHAR(1) NULL,
  `identity` DECIMAL(5,2) UNSIGNED NULL,
  `search_tool` ENUM('BLAST', 'FASTA') NULL,
  `mask` TINYINT(1) NULL,
  `evalue` DECIMAL(5,2) UNSIGNED NULL,
  `nbh_cutoff` DECIMAL(4,2) NULL,
  `min_num_hvy_atm` TINYINT UNSIGNED NULL,
  `artifacts` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compose_dataset_proj_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_compose_dataset_proj_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `napoli2`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`inter_proj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`inter_proj` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`inter_proj` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `has_submitted_files` TINYINT(1) NULL,
  `pdb_template` VARCHAR(255) NULL,
  `chain_template` CHAR(1) NULL,
  `ph` VARCHAR(45) NULL,
  `atom_prop_file` VARCHAR(255) NULL,
  `compose_dataset_proj_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `atom_prop_file_UNIQUE` (`atom_prop_file` ASC),
  INDEX `fk_inter_proj_project1_idx` (`project_id` ASC),
  INDEX `fk_inter_proj_compose_dataset_proj1_idx` (`compose_dataset_proj_id` ASC),
  CONSTRAINT `fk_inter_proj_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `napoli2`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inter_proj_compose_dataset_proj1`
    FOREIGN KEY (`compose_dataset_proj_id`)
    REFERENCES `napoli2`.`compose_dataset_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`proj_step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`proj_step` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`proj_step` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sequence` TINYINT UNSIGNED NULL,
  `title` VARCHAR(100) NULL,
  `is_critical` TINYINT(1) NULL,
  `is_parallelizable` TINYINT(1) NULL,
  `project_type_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proj_step_project_type1_idx` (`project_type_id` ASC),
  CONSTRAINT `fk_proj_step_project_type1`
    FOREIGN KEY (`project_type_id`)
    REFERENCES `napoli2`.`project_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`proj_step_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`proj_step_detail` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`proj_step_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `proj_step_id` TINYINT UNSIGNED NOT NULL,
  `status_id` TINYINT UNSIGNED NOT NULL,
  `description` VARCHAR(100) NULL,
  `progress_perc` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proj_step_has_inter_proj_proj_step1_idx` (`proj_step_id` ASC),
  INDEX `fk_inter_proj_step_detail_status1_idx` (`status_id` ASC),
  INDEX `fk_proj_step_detail_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_proj_step_has_inter_proj_proj_step1`
    FOREIGN KEY (`proj_step_id`)
    REFERENCES `napoli2`.`proj_step` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inter_proj_step_detail_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `napoli2`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proj_step_detail_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `napoli2`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`process_error`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`process_error` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`process_error` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NULL,
  `is_critical` TINYINT(1) NULL,
  `proj_step_detail_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_process_error_proj_step_detail1_idx` (`proj_step_detail_id` ASC),
  CONSTRAINT `fk_process_error_proj_step_detail1`
    FOREIGN KEY (`proj_step_detail_id`)
    REFERENCES `napoli2`.`proj_step_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`complex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`complex` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`complex` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pdb` VARCHAR(255) NULL,
  `chain` CHAR(1) NULL,
  `lig_name` CHAR(3) NULL,
  `lig_num` INT NULL,
  `cluster` INT NULL,
  `inter_proj_id` INT UNSIGNED NOT NULL,
  `status_id` TINYINT UNSIGNED NOT NULL,
  `process_error_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`, `inter_proj_id`),
  INDEX `fk_complex_inter_proj1_idx` (`inter_proj_id` ASC),
  INDEX `fk_complex_status1_idx` (`status_id` ASC),
  INDEX `fk_complex_process_error1_idx` (`process_error_id` ASC),
  CONSTRAINT `fk_complex_inter_proj1`
    FOREIGN KEY (`inter_proj_id`)
    REFERENCES `napoli2`.`inter_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complex_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `napoli2`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complex_process_error1`
    FOREIGN KEY (`process_error_id`)
    REFERENCES `napoli2`.`process_error` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`inter_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`inter_type` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`inter_type` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`pdb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`pdb` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`pdb` (
  `pdb_id` CHAR(4) NOT NULL,
  `version_date` TIMESTAMP NULL,
  `is_outdated` TINYINT(1) NULL,
  `is_obsolete` VARCHAR(45) NULL,
  `num_chains` INT UNSIGNED NULL,
  PRIMARY KEY (`pdb_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`group` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orig_comp_pdb` VARCHAR(255) NULL,
  `orig_comp_chain` CHAR(1) NULL,
  `orig_comp_name` VARCHAR(3) NULL,
  `orig_comp_num` INT NULL,
  `orig_comp_icode` CHAR(1) NULL,
  `name` VARCHAR(45) NULL,
  `coord_x` DECIMAL(8,3) NULL,
  `coord_y` DECIMAL(8,3) NULL,
  `coord_z` DECIMAL(8,3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'A group consists of 1 or more atoms, as well as an atom can participate to many groups.\n\nExample: a +charged Nitrogen in an aromatic ring participates in two groups: one aromatic group and one charged group.';


-- -----------------------------------------------------
-- Table `napoli2`.`interaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`interaction` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`interaction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id1` INT UNSIGNED NOT NULL,
  `group_id2` INT UNSIGNED NOT NULL,
  `inter_type_id` TINYINT UNSIGNED NOT NULL,
  `pdb_id` CHAR(4) NULL,
  `da_dist_hb_inter` DECIMAL(3,2) NULL,
  `ha_dist_hb_inter` DECIMAL(3,2) NULL,
  `dha_ang_hb_inter` DECIMAL(5,2) NULL,
  `dist_repuls_inter` DECIMAL(3,2) NULL,
  `dist_attract_inter` DECIMAL(3,2) NULL,
  `cc_dist_pi_pi_inter` DECIMAL(3,2) NULL,
  `dihed_ang_pi_pi_inter` DECIMAL(5,2) NULL,
  `disp_ang_pi_pi_inter` DECIMAL(5,2) NULL,
  `dist_hydrop_inter` DECIMAL(3,2) NULL,
  `xa_dist_xbond_inter` DECIMAL(3,2) NULL,
  `xc_dist_xbond_inter` DECIMAL(3,2) NULL,
  `cxa_ang_xbond_inter` DECIMAL(5,2) NULL,
  `xar_ang_xbond_inter` DECIMAL(5,2) NULL,
  `disp_ang_xbond_inter` DECIMAL(5,2) NULL,
  `dist_cation_pi_inter` DECIMAL(3,2) NULL,
  `cov_dist` DECIMAL(3,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_interaction_inter_type1_idx` (`inter_type_id` ASC),
  INDEX `fk_interaction_pdb1_idx` (`pdb_id` ASC),
  INDEX `fk_interaction_group1_idx` (`group_id1` ASC),
  INDEX `fk_interaction_group2_idx` (`group_id2` ASC),
  CONSTRAINT `fk_interaction_inter_type1`
    FOREIGN KEY (`inter_type_id`)
    REFERENCES `napoli2`.`inter_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interaction_pdb1`
    FOREIGN KEY (`pdb_id`)
    REFERENCES `napoli2`.`pdb` (`pdb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interaction_group1`
    FOREIGN KEY (`group_id1`)
    REFERENCES `napoli2`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interaction_group2`
    FOREIGN KEY (`group_id2`)
    REFERENCES `napoli2`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Each interaction has a type and involves two groups of atoms.\nAn interaction to be established also requires a set of distance and angle criterias.\nSuch values are kept to help in filtering data according to the user necessity.\n\nSome interactions belongs to a PDB obtained from the RCSB.org. In such cases, the interaction was calculated using the \ndefault parameters for pH and atom types. When an uses modifies these parameters or submit a new PDB file, the field \npdb_id would be empty, indicating the interaction is according to a user definition.';


-- -----------------------------------------------------
-- Table `napoli2`.`complex_inter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`complex_inter` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`complex_inter` (
  `complex_id` INT UNSIGNED NOT NULL,
  `interaction_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`complex_id`, `interaction_id`),
  INDEX `fk_complex_has_inter_default_inter_default1_idx` (`interaction_id` ASC),
  INDEX `fk_complex_has_inter_default_complex1_idx` (`complex_id` ASC),
  CONSTRAINT `fk_complex_has_inter_default_complex1`
    FOREIGN KEY (`complex_id`)
    REFERENCES `napoli2`.`complex` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complex_has_inter_default_inter_default1`
    FOREIGN KEY (`interaction_id`)
    REFERENCES `napoli2`.`interaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`atom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`atom` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`atom` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(4) NULL,
  `serial_number` INT NULL,
  `altloc` CHAR(1) NULL,
  `element` CHAR(1) NULL,
  `coord_x` DECIMAL(8,3) NULL,
  `coord_y` DECIMAL(8,3) NULL,
  `coord_z` DECIMAL(8,3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`field_study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`field_study` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`field_study` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`user_field_study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`user_field_study` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`user_field_study` (
  `user_id` INT UNSIGNED NOT NULL,
  `field_study_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `field_study_id`),
  INDEX `fk_user_has_field_study_field_study1_idx` (`field_study_id` ASC),
  INDEX `fk_user_has_field_study_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_field_study_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `napoli2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_field_study_field_study1`
    FOREIGN KEY (`field_study_id`)
    REFERENCES `napoli2`.`field_study` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`inter_criteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`inter_criteria` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`inter_criteria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inter_proj_id` INT UNSIGNED NOT NULL,
  `max_da_dist_hb_inter` DECIMAL(3,2) NULL,
  `max_ha_dist_hb_inter` DECIMAL(3,2) NULL,
  `min_dha_ang_hb_inter` DECIMAL(5,2) NULL,
  `min_dist_repuls_inter` DECIMAL(3,2) NULL,
  `max_dist_repuls_inter` DECIMAL(3,2) NULL,
  `min_dist_attract_inter` DECIMAL(3,2) NULL,
  `max_dist_attract_inter` DECIMAL(3,2) NULL,
  `max_cc_dist_pi_pi_inter` DECIMAL(3,2) NULL,
  `min_dihed_ang_pi_pi_inter` DECIMAL(5,2) NULL,
  `max_disp_ang_pi_pi_inter` DECIMAL(5,2) NULL,
  `min_dist_hydrop_inter` DECIMAL(3,2) NULL,
  `max_dist_hydrop_inter` DECIMAL(3,2) NULL,
  `max_xa_dist_xbond_inter` DECIMAL(3,2) NULL,
  `max_xc_dist_xbond_inter` DECIMAL(3,2) NULL,
  `min_cxa_ang_xbond_inter` DECIMAL(5,2) NULL,
  `min_xar_ang_xbond_inter` DECIMAL(5,2) NULL,
  `max_disp_ang_xbond_inter` DECIMAL(5,2) NULL,
  `min_dist_cation_pi_inter` DECIMAL(3,2) NULL,
  `max_dist_cation_pi_inter` DECIMAL(3,2) NULL,
  `boundary_cutoff` DECIMAL(3,2) NULL,
  `cov_dist_tolerance` DECIMAL(3,2) NULL,
  PRIMARY KEY (`id`, `inter_proj_id`),
  INDEX `fk_inter_criteria_inter_proj1_idx` (`inter_proj_id` ASC),
  CONSTRAINT `fk_inter_criteria_inter_proj1`
    FOREIGN KEY (`inter_proj_id`)
    REFERENCES `napoli2`.`inter_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'An user can change the interaction criterias';


-- -----------------------------------------------------
-- Table `napoli2`.`university`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`university` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`university` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`inter_viewer_conf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`inter_viewer_conf` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`inter_viewer_conf` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inter_proj_id` INT UNSIGNED NOT NULL,
  `file` VARCHAR(255) NOT NULL,
  INDEX `fk_inter_viewer_conf_inter_proj1_idx` (`inter_proj_id` ASC),
  PRIMARY KEY (`id`, `inter_proj_id`),
  CONSTRAINT `fk_inter_viewer_conf_inter_proj1`
    FOREIGN KEY (`inter_proj_id`)
    REFERENCES `napoli2`.`inter_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`group_atom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`group_atom` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`group_atom` (
  `group_id` INT UNSIGNED NOT NULL,
  `atom_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`group_id`, `atom_id`),
  INDEX `fk_group_has_atom_atom1_idx` (`atom_id` ASC),
  INDEX `fk_group_has_atom_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_has_atom_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `napoli2`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_atom_atom1`
    FOREIGN KEY (`atom_id`)
    REFERENCES `napoli2`.`atom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`inter_depend_inter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`inter_depend_inter` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`inter_depend_inter` (
  `interaction_id` INT UNSIGNED NOT NULL,
  `interaction_id1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`interaction_id`, `interaction_id1`),
  INDEX `fk_interaction_has_interaction_interaction2_idx` (`interaction_id1` ASC),
  INDEX `fk_interaction_has_interaction_interaction1_idx` (`interaction_id` ASC),
  CONSTRAINT `fk_interaction_has_interaction_interaction1`
    FOREIGN KEY (`interaction_id`)
    REFERENCES `napoli2`.`interaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interaction_has_interaction_interaction2`
    FOREIGN KEY (`interaction_id1`)
    REFERENCES `napoli2`.`interaction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Some interactions depend on other interactions to occur. \n\nFor example, a \'water bridged hydrogen bond\' depends on two hydrogen bonds to occur: \none between the protein and the water, and other between the ligand and the water.\nSo, when we say that a protein and a ligand establish such interaction, it doesn\'t mean that\nthere is a direct interaction between this two molecules. Actually, it is a simplification and indicates\nimplicitly that there are at least two hydrogen bonds.\n';


-- -----------------------------------------------------
-- Table `napoli2`.`entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`entry` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`entry` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pdb_id` CHAR(4) NOT NULL,
  `compose_dataset_proj_id` INT UNSIGNED NOT NULL,
  `status_id` TINYINT UNSIGNED NOT NULL,
  `process_error_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recovered_pdb_status1_idx` (`status_id` ASC),
  INDEX `fk_recovered_pdb_process_error1_idx` (`process_error_id` ASC),
  INDEX `fk_entry_pdb1_idx` (`pdb_id` ASC),
  INDEX `fk_entry_compose_dataset_proj1_idx` (`compose_dataset_proj_id` ASC),
  CONSTRAINT `fk_recovered_pdb_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `napoli2`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recovered_pdb_process_error1`
    FOREIGN KEY (`process_error_id`)
    REFERENCES `napoli2`.`process_error` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entry_pdb1`
    FOREIGN KEY (`pdb_id`)
    REFERENCES `napoli2`.`pdb` (`pdb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entry_compose_dataset_proj1`
    FOREIGN KEY (`compose_dataset_proj_id`)
    REFERENCES `napoli2`.`compose_dataset_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`ci_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`ci_session` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`ci_session` (
  `id` VARCHAR(128) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ci_sessions_timestamp` (`timestamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`compound_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`compound_type` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`compound_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`interacting_res_by_cluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`interacting_res_by_cluster` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`interacting_res_by_cluster` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cluster` TINYINT UNSIGNED NULL,
  `resname` CHAR(3) NULL,
  `resnum` INT NULL,
  `resicode` CHAR(1) NULL,
  `inter_residue_id` INT UNSIGNED NULL,
  `inter_proj_id` INT UNSIGNED NOT NULL,
  `num_lig_hb_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_hbw_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_hydrop_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_repuls_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_attract_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_xbond_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_pi_cation_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_pi_pi_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `num_lig_salt_bdg_inter` INT UNSIGNED NOT NULL DEFAULT 0,
  `total_num_lig` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `inter_proj_id`),
  INDEX `fk_inter_residue_inter_residue1_idx` (`inter_residue_id` ASC),
  INDEX `fk_inter_residue_inter_proj1_idx` (`inter_proj_id` ASC),
  CONSTRAINT `fk_inter_residue_inter_residue1`
    FOREIGN KEY (`inter_residue_id`)
    REFERENCES `napoli2`.`interacting_res_by_cluster` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inter_residue_inter_proj1`
    FOREIGN KEY (`inter_proj_id`)
    REFERENCES `napoli2`.`inter_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`chain_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`chain_type` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`chain_type` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = 'Chain type: RNA, DNA, protein, polypeptide, etc...';


-- -----------------------------------------------------
-- Table `napoli2`.`chain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`chain` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`chain` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pdb_id` CHAR(4) NOT NULL,
  `chain` CHAR(1) NULL,
  `num_res` INT UNSIGNED NULL,
  `chain_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chain_pdb1_idx` (`pdb_id` ASC),
  INDEX `fk_chain_chain_type1_idx` (`chain_type_id` ASC),
  CONSTRAINT `fk_chain_pdb1`
    FOREIGN KEY (`pdb_id`)
    REFERENCES `napoli2`.`pdb` (`pdb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chain_chain_type1`
    FOREIGN KEY (`chain_type_id`)
    REFERENCES `napoli2`.`chain_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`ligand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`ligand` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`ligand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chain_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(3) NULL,
  `num` VARCHAR(45) NULL,
  `icode` VARCHAR(45) NULL,
  `num_heavy_atoms` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ligand_chain1_idx` (`chain_id` ASC),
  CONSTRAINT `fk_ligand_chain1`
    FOREIGN KEY (`chain_id`)
    REFERENCES `napoli2`.`chain` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`mol_fp_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`mol_fp_type` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`mol_fp_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`ligand_fp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`ligand_fp` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`ligand_fp` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ligand_id` INT UNSIGNED NOT NULL,
  `bits` VARCHAR(255) NULL,
  `mol_fp_type_id` INT UNSIGNED NOT NULL,
  INDEX `fk_fingerprint_ligand1_idx` (`ligand_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_ligand_fp_mol_fp_type1_idx` (`mol_fp_type_id` ASC),
  CONSTRAINT `fk_fingerprint_ligand1`
    FOREIGN KEY (`ligand_id`)
    REFERENCES `napoli2`.`ligand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligand_fp_mol_fp_type1`
    FOREIGN KEY (`mol_fp_type_id`)
    REFERENCES `napoli2`.`mol_fp_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`ligand_found`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`ligand_found` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`ligand_found` (
  `compose_dataset_proj_id` INT UNSIGNED NOT NULL,
  `ligand_id` INT UNSIGNED NOT NULL,
  `is_art_crystal` TINYINT(1) NULL,
  `region_num` INT UNSIGNED NULL,
  PRIMARY KEY (`compose_dataset_proj_id`, `ligand_id`),
  INDEX `fk_compose_dataset_proj_has_ligand_ligand1_idx` (`ligand_id` ASC),
  INDEX `fk_compose_dataset_proj_has_ligand_compose_dataset_proj1_idx` (`compose_dataset_proj_id` ASC),
  CONSTRAINT `fk_compose_dataset_proj_has_ligand_compose_dataset_proj1`
    FOREIGN KEY (`compose_dataset_proj_id`)
    REFERENCES `napoli2`.`compose_dataset_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compose_dataset_proj_has_ligand_ligand1`
    FOREIGN KEY (`ligand_id`)
    REFERENCES `napoli2`.`ligand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`pdb_chain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`pdb_chain` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`pdb_chain` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pdb_id` VARCHAR(255) NULL,
  `chain` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`res_belongs_to`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`res_belongs_to` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`res_belongs_to` (
  `interacting_res_id` INT UNSIGNED NOT NULL,
  `pdb_chain_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`interacting_res_id`, `pdb_chain_id`),
  INDEX `fk_interacting_res_has_pdb_chain_pdb_chain1_idx` (`pdb_chain_id` ASC),
  INDEX `fk_interacting_res_has_pdb_chain_interacting_res1_idx` (`interacting_res_id` ASC),
  CONSTRAINT `fk_interacting_res_has_pdb_chain_interacting_res1`
    FOREIGN KEY (`interacting_res_id`)
    REFERENCES `napoli2`.`interacting_res_by_cluster` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interacting_res_has_pdb_chain_pdb_chain1`
    FOREIGN KEY (`pdb_chain_id`)
    REFERENCES `napoli2`.`pdb_chain` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`group_freq_by_cluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`group_freq_by_cluster` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`group_freq_by_cluster` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inter_proj_id` INT UNSIGNED NOT NULL,
  `cluster` INT NULL,
  `compound_type_id` INT UNSIGNED NOT NULL,
  `total_num_group` VARCHAR(45) NULL,
  `total_num_lig` INT NULL,
  PRIMARY KEY (`id`, `inter_proj_id`),
  INDEX `fk_group_freq_by_cluster_compound_type1_idx` (`compound_type_id` ASC),
  INDEX `fk_group_freq_by_cluster_inter_proj1_idx` (`inter_proj_id` ASC),
  CONSTRAINT `fk_group_freq_by_cluster_compound_type1`
    FOREIGN KEY (`compound_type_id`)
    REFERENCES `napoli2`.`compound_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_freq_by_cluster_inter_proj1`
    FOREIGN KEY (`inter_proj_id`)
    REFERENCES `napoli2`.`inter_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`inter_freq_by_cluster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`inter_freq_by_cluster` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`inter_freq_by_cluster` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `inter_proj_id` INT UNSIGNED NOT NULL,
  `cluster` INT NULL,
  `inter_type_id` TINYINT UNSIGNED NOT NULL,
  `num_num_inter` INT NULL,
  `total_num_lig` INT NULL,
  PRIMARY KEY (`id`, `inter_proj_id`),
  INDEX `fk_inter_freq_by_cluster_inter_proj2_idx` (`inter_proj_id` ASC),
  INDEX `fk_inter_freq_by_cluster_inter_type1_idx` (`inter_type_id` ASC),
  CONSTRAINT `fk_inter_freq_by_cluster_inter_proj2`
    FOREIGN KEY (`inter_proj_id`)
    REFERENCES `napoli2`.`inter_proj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inter_freq_by_cluster_inter_type1`
    FOREIGN KEY (`inter_type_id`)
    REFERENCES `napoli2`.`inter_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`group_compound_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`group_compound_type` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`group_compound_type` (
  `compound_type_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`compound_type_id`, `group_id`),
  INDEX `fk_compound_type_has_group_group1_idx` (`group_id` ASC),
  INDEX `fk_compound_type_has_group_compound_type1_idx` (`compound_type_id` ASC),
  CONSTRAINT `fk_compound_type_has_group_compound_type1`
    FOREIGN KEY (`compound_type_id`)
    REFERENCES `napoli2`.`compound_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compound_type_has_group_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `napoli2`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`comp_type_count`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`comp_type_count` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`comp_type_count` (
  `complex_id` INT UNSIGNED NOT NULL,
  `complex_inter_proj_id` INT UNSIGNED NOT NULL,
  `compound_type_id` INT UNSIGNED NOT NULL,
  `total` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`complex_id`, `complex_inter_proj_id`),
  INDEX `fk_comp_type_count_compound_type1_idx` (`compound_type_id` ASC),
  INDEX `fk_comp_type_count_complex1_idx` (`complex_id` ASC, `complex_inter_proj_id` ASC),
  CONSTRAINT `fk_comp_type_count_compound_type1`
    FOREIGN KEY (`compound_type_id`)
    REFERENCES `napoli2`.`compound_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comp_type_count_complex1`
    FOREIGN KEY (`complex_id` , `complex_inter_proj_id`)
    REFERENCES `napoli2`.`complex` (`id` , `inter_proj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `napoli2`.`inter_type_count`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `napoli2`.`inter_type_count` ;

CREATE TABLE IF NOT EXISTS `napoli2`.`inter_type_count` (
  `id` INT UNSIGNED NOT NULL,
  `complex_id` INT UNSIGNED NOT NULL,
  `complex_inter_proj_id` INT UNSIGNED NOT NULL,
  `inter_type_id` TINYINT UNSIGNED NOT NULL,
  `total` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `complex_id`, `complex_inter_proj_id`),
  INDEX `fk_inter_type_count_inter_type1_idx` (`inter_type_id` ASC),
  INDEX `fk_inter_type_count_complex1_idx` (`complex_id` ASC, `complex_inter_proj_id` ASC),
  CONSTRAINT `fk_inter_type_count_inter_type1`
    FOREIGN KEY (`inter_type_id`)
    REFERENCES `napoli2`.`inter_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inter_type_count_complex1`
    FOREIGN KEY (`complex_id` , `complex_inter_proj_id`)
    REFERENCES `napoli2`.`complex` (`id` , `inter_proj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `napoli2`.`inter_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `napoli2`;
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Hydrogen bond');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Attractive');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Salt bridge');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Cation-pi');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Edge-to-face pi-stacking');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Face-to-face pi-stacking');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Parallel-displaced pi-stacking');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Hydrophobic');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Halogen bond');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Repulsive');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Water-bridged hydrogen bond');
INSERT INTO `napoli2`.`inter_type` (`id`, `type`) VALUES (DEFAULT, 'Pi-stacking');

COMMIT;


-- -----------------------------------------------------
-- Data for table `napoli2`.`compound_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `napoli2`;
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Aromatic');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Acceptor');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Donor');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Hydrophobe');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Hydrophobic');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Negative');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Positive');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Negative ionizable');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Positive ionizable');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Halogen donor');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Halogen acceptor');
INSERT INTO `napoli2`.`compound_type` (`id`, `type`) VALUES (DEFAULT, 'Metal');

COMMIT;

