name: luna-env
channels:
  - anaconda
  - schrodinger
  - conda-forge
  - defaults
dependencies:
  - python
  - rdkit
  - seaborn
  - openbabel
  - pip
  - biopython>=1.77
  - pymol
  - xopen
  - colorlog
  - networkx
  - scipy
  - pip:
    - babel==2.8.0
    - mmh3==2.5.1
    - sphinxcontrib-programoutput